### ISSUE TITLE
Thread Problems

### ISSUE THREAD

**Issue by dendisuhubdy** [TScottJ/OpenEphyra#6]
Exception in thread "Thread-10" Exception in thread "Thread-1" Exception in thread "Thread-7" Exception in thread "Thread-5" Exception in thread "Thread-2" java.lang.NullPointerException
    at info.ephyra.search.searchers.BingKM.doSearch(BingKM.java:83)
    at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
Exception in thread "Thread-9" Exception in thread "Thread-12" Exception in thread "Thread-6" java.lang.NullPointerException
    at info.ephyra.search.searchers.BingKM.doSearch(BingKM.java:83)
    at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NullPointerException
    at info.ephyra.search.searchers.BingKM.doSearch(BingKM.java:83)
    at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NullPointerException
    at info.ephyra.search.searchers.BingKM.doSearch(BingKM.java:83)
    at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NullPointerException
    at info.ephyra.search.searchers.BingKM.doSearch(BingKM.java:83)
    at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NullPointerException
    at info.ephyra.search.searchers.BingKM.doSearch(BingKM.java:83)
    at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
Exception in thread "Thread-3" java.lang.NullPointerException
    at info.ephyra.search.searchers.BingKM.doSearch(BingKM.java:83)
    at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NullPointerException
    at info.ephyra.search.searchers.BingKM.doSearch(BingKM.java:83)
    at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NullPointerException
    at info.ephyra.search.searchers.BingKM.doSearch(BingKM.java:83)
    at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
Exception in thread "Thread-8" Exception in thread "Thread-11" Exception in thread "Thread-4" java.lang.NullPointerException
    at info.ephyra.search.searchers.BingKM.doSearch(BingKM.java:83)
    at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NullPointerException
    at info.ephyra.search.searchers.BingKM.doSearch(BingKM.java:83)
    at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NullPointerException
    at info.ephyra.search.searchers.BingKM.doSearch(BingKM.java:83)
    at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)

**Comment by vivektiwari1986** [comment]
I have added a apull request to fix this issue. You could try using my fork and see if it works. You need to have your bing web search api key in BingAzureKM.java though
