### ISSUE TITLE
OpenEphyra.sh execution failed Could not find or load main class info.ephyra.OpenEphyra

### ISSUE THREAD

**Issue by dendisuhubdy** [TScottJ/OpenEphyra#7]
C02QH2D7G8WM:scripts admin$ ./OpenEphyra.sh
Error: Could not find or load main class info.ephyra.OpenEphyra

**Comment by vivektiwari1986** [comment]
Do you have a compiled jar in the directory?

**Comment by tanmayb123** [comment]
Hi - I had this issue, just go one directory out of "scripts" (where the README is), and run the "ant" command...

**Comment by PraveenkumarDonga** [comment]
Hi! tanmay,
I ran the command "ant". but still it is not working.
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
    The method format(Date) in the type DateFormat is not applicable for the arguments (long)

```
at info.ephyra.io.MsgPrinter.getTimestamp(MsgPrinter.java:421)
at info.ephyra.io.MsgPrinter.printInitializing(MsgPrinter.java:107)
at info.ephyra.OpenEphyra.<init>(OpenEphyra.java:131)
at info.ephyra.OpenEphyra.<init>(OpenEphyra.java:102)
at info.ephyra.OpenEphyra.main(OpenEphyra.java:88)
```

Please help me with this 
Thanks,
Praveen.

**Comment by PraveenkumarDonga** [comment]
Hi! vivektiwari,
I didn't get your point.
what is that compiled jar?

Please help me with this 
Thanks,
Praveen.

**Comment by tanmayb123** [comment]
Hi - what OS are you running?

**Comment by PraveenkumarDonga** [comment]
Hi! Tanmay,
I am using ubuntu14.04.

**Comment by tanmayb123** [comment]
Alright, thanks! I'll get that on a VM, test it out, record it, and send it to you.
